repos:
  - name: junit4
    url: https://github.com/junit-team/junit4.git
    max_scenarios: 50

  - name: commons-lang
    url: https://github.com/apache/commons-lang.git
    max_scenarios: 50

  - name: javaparser
    url: https://github.com/javaparser/javaparser.git
    max_scenarios: 50

  - name: error-prone
    url: https://github.com/google/error-prone.git
    max_scenarios: 50
